version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecomuser
      MYSQL_PASSWORD: ecom_pass123
    ports:
      - "3307:3306"  # host:container
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecommerce-phpmyadmin
    restart: always
    ports:
      - "8080:80"  # http://localhost:8080
    environment:
      PMA_HOST: mysql
      PMA_USER: ecomuser
      PMA_PASSWORD: ecom_pass123
